# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2025 FexTel, Inc. <info@ibscale.com>
# Author: James Pearson <jamesp@ibscale.com>

# eeprom_at21cs01.py - Microchip AT21CS01 single-wire EEPROM driver (128 bytes).
#
# Implemented from the Microchip datasheet DS20005857 - the AT21CS01 is NOT
# a Dallas 1-Wire device. It emulates the I2C protocol over one open-drain wire:
# every transaction is a Start (line idle high >= tHTSS), then bytes MSB-first,
# each followed by an ACK(0)/NACK(1) bit from the receiver. The device address
# byte is [4-bit opcode | A2 A1 A0 client address | R/W#]; the client address is
# factory-set by ordering code (-xxxM10 parts = 000). Pages are 8 bytes; a write
# that crosses a page boundary wraps WITHIN the page, so writes must be split.
# The self-timed write cycle is tWR <= 5 ms after the Stop.
#
# The device powers up / resets into High-Speed mode (DS 7.6.2). This driver
# performs Reset + Discovery Response (DS 4.1.1, High-Speed timing always applies
# there), then switches the part to Standard Speed mode (~15.4 kbps, AT21CS01
# only) for 4x more timing margin and runs all traffic there. If the part NACKs
# Standard Speed (an AT21CS11 would), it falls back to High-Speed mode.
#
# Bit waveforms are generated by calibrated @micropython.viper spin loops writing
# GPIO BSRR/IDR directly, with IRQs disabled for the duration of each bus
# transaction (worst case ~6 ms for a full 8-byte page write; gaps longer than
# max tBIT abort a command mid-stream, so per-byte Python pacing is not an
# option). EEPROM traffic only happens at boot and when a floor address is
# programmed, so the IRQ-off windows are rare.
#
# !!! Timing constants are mid-window values from DS20005857 section 3.5 and the
# !!! High-Speed read-sample point is inherently tight (tMRS <= 2us) - verify on
# !!! hardware with a scope before trusting this driver in production.

import time
import machine
import micropython
from array import array

# Opcodes (DS table 6-1)
_OP_EEPROM = micropython.const(0xA)      # main array read/write
_OP_SECURITY = micropython.const(0xB)    # security register (serial number)
_OP_MFR_ID = micropython.const(0xC)      # manufacturer ID read
_OP_STD_SPEED = micropython.const(0xD)   # switch/query Standard Speed (CS01 only)
_OP_HIGH_SPEED = micropython.const(0xE)  # switch/query High-Speed

_MFR_ID_AT21CS01 = micropython.const(0x00D200)  # DS table 8-2
_MFR_ID_AT21CS11 = micropython.const(0x00D380)

_PAGE_SIZE = micropython.const(8)
_TWR_MS = micropython.const(6)           # self-timed write cycle, tWR max 5ms + margin

# Bit timings in us, mid-window from DS20005857 section 3.5.2.
# (low0, low1, bit, rd, sample-from-fall, htss)
_T_STD = (30.0, 6.0, 60.0, 5.0, 7.0, 700)    # tLOW0 24-64, tLOW1 4-8, tBIT 40-100, tMRS<=8, tHTSS>=600
_T_HS = (10.0, 1.5, 20.0, 1.0, 1.8, 200)     # tLOW0 6-16, tLOW1 1-2, tBIT<=25, tMRS<=2, tHTSS>=150

# cfg array('I') layout shared with the viper routines:
# 0 BSRR addr, 1 IDR addr, 2 set(release) mask, 3 reset(drive-low) mask,
# 4 low0 spins, 5 rest0 spins, 6 low1 spins, 7 rest1 spins,
# 8 rd spins, 9 sample-delta spins, 10 rest-after-sample spins, 11 IDR pin mask,
# 12 tDRR spins, 13 discovery sample-delta spins, 14 discovery tail spins


@micropython.viper
def _spin(n: int):
    while n > 0:
        n -= 1


@micropython.viper
def _txn(cfg: ptr32, buf: ptr8, ntx: int, nrx: int) -> int:
    """One bus transaction: send buf[0:ntx] checking each ACK, then read nrx bytes
    into buf[ntx:], host-ACKing all but the last (NACK ends the read, DS 8.1).
    Returns nrx on success or -(1+index) for a NACKed TX byte. Caller must hold
    the line idle-high >= tHTSS beforehand (Start) and disable IRQs around this.
    """
    bsrr = ptr32(cfg[0])
    idr = ptr32(cfg[1])
    setm = cfg[2]
    rstm = cfg[3]
    pmask = cfg[11]

    for i in range(ntx):
        b = int(buf[i])
        m = 0x80
        while m != 0:
            bsrr[0] = rstm                      # falling edge starts the bit frame
            if (b & m) != 0:
                n = cfg[6]
            else:
                n = cfg[4]
            while n > 0:
                n -= 1
            bsrr[0] = setm                      # release
            if (b & m) != 0:
                n = cfg[7]
            else:
                n = cfg[5]
            while n > 0:
                n -= 1
            m >>= 1
        # Client ACK bit (output frame: short request low, sample, ride out frame)
        bsrr[0] = rstm
        n = cfg[8]
        while n > 0:
            n -= 1
        bsrr[0] = setm
        n = cfg[9]
        while n > 0:
            n -= 1
        v = idr[0] & pmask
        n = cfg[10]
        while n > 0:
            n -= 1
        if v != 0:                              # line high at sample = NACK
            return 0 - (i + 1)

    for j in range(nrx):
        b = 0
        for _ in range(8):
            bsrr[0] = rstm
            n = cfg[8]
            while n > 0:
                n -= 1
            bsrr[0] = setm
            n = cfg[9]
            while n > 0:
                n -= 1
            bit = 0
            if (idr[0] & pmask) != 0:
                bit = 1
            b = (b << 1) | bit
            n = cfg[10]
            while n > 0:
                n -= 1
        buf[ntx + j] = b
        # Host ACK (logic 0) after each byte, NACK (logic 1) after the last
        bsrr[0] = rstm
        if j == nrx - 1:
            n = cfg[6]
        else:
            n = cfg[4]
        while n > 0:
            n -= 1
        bsrr[0] = setm
        if j == nrx - 1:
            n = cfg[7]
        else:
            n = cfg[5]
        while n > 0:
            n -= 1
    return nrx


@micropython.viper
def _discovery(cfg: ptr32) -> int:
    """Discovery Response Request (DS 4.1.1.2, High-Speed timing): drive low tDRR,
    release, sample within the tMSDR window - a present device concurrently drives
    the line low for tDACK. Returns 1 if a device acknowledged. Caller handles the
    preceding reset low period and tRRT, and disables IRQs around this."""
    bsrr = ptr32(cfg[0])
    idr = ptr32(cfg[1])
    bsrr[0] = cfg[3]        # request: drive low for tDRR
    n = cfg[12]
    while n > 0:
        n -= 1
    bsrr[0] = cfg[2]        # release
    n = cfg[13]
    while n > 0:
        n -= 1
    v = idr[0] & cfg[11]    # low = device holding the line (tDACK)
    n = cfg[14]             # ride out the rest of tDACK before any Start
    while n > 0:
        n -= 1
    if v == 0:
        return 1
    return 0


class AT21CS01:
    """Microchip AT21CS01/AT21CS11 single-wire EEPROM (128 x 8, 8-byte pages)."""

    def __init__(self, pin_name, DMESG=None, LOG=False, slave_addr=0):
        self.DMESG, self.LOG = DMESG, LOG
        self._present = False
        self._addr = slave_addr & 0x07   # -xxxM10 ordering codes are client address 000
        self._speed = None
        self._buf = bytearray(20)        # max txn: 2 addr + 8 data tx, or 1 tx + 8 rx

        try:
            # Open-drain with pull-up external; value 1 = released. machine.Pin is
            # pyb.Pin on stm32, so .gpio()/.pin() expose the port registers for viper.
            self.pin = machine.Pin(pin_name, machine.Pin.OPEN_DRAIN, value=1)
            gpio = self.pin.gpio()
            num = self.pin.pin()
            self._cfg = array('I', [0] * 15)
            self._cfg[0] = gpio + 0x18                   # BSRR
            self._cfg[1] = gpio + 0x10                   # IDR
            self._cfg[2] = 1 << num                      # BSRR set = release
            self._cfg[3] = 1 << (num + 16)               # BSRR reset = drive low
            self._cfg[11] = 1 << num                     # IDR mask

            self._lpu = self._calibrate()                # spin-loop iterations per us
            # Discovery timing (always High-Speed, DS note 3): tDRR 1-2us, sample
            # inside tMSDR 2-6us from the falling edge, then outlast tDACK (<=24us).
            self._cfg[12] = self._spins(1.2)
            self._cfg[13] = self._spins(1.3)             # sample at ~2.5us from fall
            self._cfg[14] = self._spins(30.0)

            if not self._reset_discover():
                self._log(f"WARN - Pin:{pin_name}, No discovery response", force=True)
                return
            if not self._attach():
                self._log(f"WARN - Pin:{pin_name}, Discovery OK but no opcode ACK " +
                          f"(client address/speed?)", force=True)
                return
            self._present = True
            mfr = self._read_mfr_id()
            if mfr == _MFR_ID_AT21CS01:
                name = "AT21CS01"
            elif mfr == _MFR_ID_AT21CS11:
                name = "AT21CS11"
            else:
                name = f"unknown (mfr={mfr:#08x})" if mfr is not None else "unknown (no mfr ID)"
            self._log(f"OK - Pin:{pin_name}, {name}, addr={self._addr}, " +
                      f"mode={self._speed}", force=True)
        except Exception as e:
            self._log(f"FAIL - Pin:{pin_name}, Error:{e}", force=True)

    def _log(self, msg, force=False):
        if (self.LOG or force) and self.DMESG:
            self.DMESG.log(f"EEPROM[AT21CS01]: {msg}")

    # --- Low level ---------------------------------------------------------

    def _calibrate(self):
        """Measure viper spin-loop iterations per microsecond (IRQs off)."""
        _spin(1000)  # touch the code path once first
        state = machine.disable_irq()
        try:
            t0 = time.ticks_us()
            _spin(50000)
            dt = time.ticks_diff(time.ticks_us(), t0)
        finally:
            machine.enable_irq(state)
        if dt <= 0:
            raise RuntimeError("spin calibration failed")
        return 50000 / dt

    def _spins(self, us):
        n = int(us * self._lpu)
        return n if n >= 1 else 1

    def _use_speed(self, t):
        """Load bit timings (low0, low1, bit, rd, sample, htss) into the viper cfg."""
        low0, low1, bit, rd, smp, htss = t
        self._cfg[4] = self._spins(low0)
        self._cfg[5] = self._spins(bit - low0)
        self._cfg[6] = self._spins(low1)
        self._cfg[7] = self._spins(bit - low1)
        self._cfg[8] = self._spins(rd)
        self._cfg[9] = self._spins(smp - rd)
        self._cfg[10] = self._spins(bit - smp)
        self._t_htss = htss

    def _transact(self, tx, nrx):
        """Start condition (idle high >= tHTSS), then one IRQ-off viper transaction.
        Returns nrx on success, negative NACK index from _txn otherwise."""
        n = len(tx)
        self._buf[0:n] = bytes(tx)
        time.sleep_us(self._t_htss)
        state = machine.disable_irq()
        try:
            return _txn(self._cfg, self._buf, n, nrx)
        finally:
            machine.enable_irq(state)

    def _devbyte(self, opcode, rw):
        return (opcode << 4) | (self._addr << 1) | rw

    # --- Bring-up ----------------------------------------------------------

    def _reset_discover(self):
        """Reset (low >= tRESET, covers both speed modes) then Discovery Response."""
        self.pin.value(0)
        time.sleep_us(500)          # tRESET: >=480us standard / >=96us high-speed
        self.pin.value(1)
        time.sleep_us(20)           # tRRT >= 8us after release
        state = machine.disable_irq()
        try:
            found = _discovery(self._cfg)
        finally:
            machine.enable_irq(state)
        time.sleep_us(200)          # tHTSS (high-speed) before the first command
        return found == 1

    def _attach(self):
        """Find the client address and put the device in a known speed mode.

        The part is in High-Speed mode after reset. For each candidate address:
        send 'switch to Standard Speed' at High-Speed timing (ACK sampling at HS
        is marginal, so the result is ignored), then query Standard Speed mode at
        Standard timing - an ACK proves both the address and the mode switch.
        Falls back to High-Speed-only operation (AT21CS11 NACKs Standard Speed).
        """
        order = [self._addr] + [a for a in range(8) if a != self._addr]
        for a in order:
            self._addr = a
            self._use_speed(_T_HS)
            self._transact([self._devbyte(_OP_STD_SPEED, 0)], 0)   # best effort
            self._use_speed(_T_STD)
            if self._transact([self._devbyte(_OP_STD_SPEED, 1)], 0) == 0:
                self._speed = 'std'
                return True
        self._use_speed(_T_HS)
        for a in order:
            self._addr = a
            if self._transact([self._devbyte(_OP_HIGH_SPEED, 1)], 0) == 0:
                self._speed = 'hs'
                return True
        return False

    def _read_mfr_id(self):
        """Manufacturer ID read (opcode Ch + R): 3 bytes, 0x00D200 for AT21CS01."""
        ret = self._transact([self._devbyte(_OP_MFR_ID, 1)], 3)
        if ret != 3:
            return None
        return (self._buf[1] << 16) | (self._buf[2] << 8) | self._buf[3]

    # --- Public API (same surface as the DS28E07 driver) --------------------

    def read_memory(self, addr, length):
        """Random read: dummy write sets the address pointer, then current-address
        reads pull the data out in <=8-byte transactions (bounds the IRQ-off time;
        the pointer advances across reads, DS section 8)."""
        if not self._present:
            return None
        if not (0 <= addr <= 127 and 0 < length <= 128 - addr):
            self._log(f"Invalid read params: addr={addr}, len={length}")
            return None
        try:
            if self._transact([self._devbyte(_OP_EEPROM, 0), addr & 0x7F], 0) != 0:
                self._log(f"Read @{addr}: address NACKed")
                return None
            out = b''
            remaining = length
            while remaining:
                n = min(remaining, 8)
                if self._transact([self._devbyte(_OP_EEPROM, 1)], n) != n:
                    self._log(f"Read @{addr}: data phase NACKed")
                    return None
                out += bytes(self._buf[1:1 + n])
                remaining -= n
            self._log(f"Read {length}B @ {addr}")
            return out
        except Exception as e:
            self._log(f"Read error: {e}")
            return None

    def write_memory(self, addr, data):
        """Page-split write with tWR wait per page and a read-back verify. A write
        crossing an 8-byte page boundary would wrap within the page (DS 7.3), so
        chunks never cross one."""
        if not self._present:
            return False
        if not isinstance(data, (bytes, bytearray)):
            data = bytes(data)
        if not (0 <= addr <= 127 and 0 < len(data) <= 128 - addr):
            self._log(f"Invalid write params: addr={addr}, len={len(data)}")
            return False
        try:
            pos = 0
            while pos < len(data):
                a = addr + pos
                page_room = _PAGE_SIZE - (a % _PAGE_SIZE)
                n = min(len(data) - pos, page_room)
                tx = [self._devbyte(_OP_EEPROM, 0), a & 0x7F] + list(data[pos:pos + n])
                ret = self._transact(tx, 0)
                if ret != 0:
                    self._log(f"Write @{a}: NACK at byte {-ret - 1}")
                    return False
                # Stop already happened (line idle after the txn); self-timed
                # write cycle runs now - no bus traffic allowed until tWR passes.
                time.sleep_ms(_TWR_MS)
                pos += n
            verify = self.read_memory(addr, len(data))
            if verify != bytes(data):
                self._log(f"Verify failed @ {addr}")
                return False
            self._log(f"Wrote {len(data)}B @ {addr}")
            return True
        except Exception as e:
            self._log(f"Write error: {e}")
            return False
