# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2025 FexTel, Inc. <info@ibscale.com>
# Author: James Pearson <jamesp@ibscale.com>

# eeprom_ds28e07.py - Maxim/ADI DS28E07 1-Wire EEPROM driver (128 bytes user memory).
#
# Implemented from the DS28E07 datasheet (Maxim 19-100086 / ADI). Points that make
# or break this device (and that a naive DS24xx-style driver gets wrong):
#  - Copies are FULL-ROW ONLY: the Write Scratchpad target address must be 8-byte
#    aligned (T[2:0] = 000b) and exactly 8 data bytes must be written, otherwise
#    the PF flag stays set and Copy Scratchpad silently does nothing. Arbitrary
#    writes therefore require read-modify-write of each affected 8-byte row.
#  - The device generates an inverted Dallas CRC-16 (poly 0x8005), transmitted
#    LSB first: after Write Scratchpad (over [0Fh, TA1, TA2, data...], available
#    only when the scratchpad filled to E[2:0]=111b) and after Read Scratchpad
#    (over [AAh, TA1, TA2, E/S, data...]).
#  - Copy Scratchpad requires the 3-byte authorization pattern TA1, TA2, E/S
#    exactly as read back, takes tPROG (10ms max) during which the bus must idle
#    high (parasite power - keep RPUP <= 2.2k), then transmits alternating 0s and
#    1s until the next reset.
#  - ROM ID: family code 2Dh + 48-bit serial + CRC8, readable with READ ROM (33h)
#    on a single-drop bus (this driver assumes one device, hence SKIP ROM).

import time
from machine import Pin
import onewire
from hardware.eeprom import crc8

_ROW = 8
_TPROG_MS = 10          # EEPROM programming time, datasheet max
_FAMILY_CODE = 0x2D

_CMD_WRITE_SCRATCHPAD = 0x0F
_CMD_READ_SCRATCHPAD = 0xAA
_CMD_COPY_SCRATCHPAD = 0x55
_CMD_READ_MEMORY = 0xF0
_CMD_SKIP_ROM = 0xCC
_CMD_READ_ROM = 0x33


def crc16(data, crc=0):
    """Dallas/Maxim CRC-16, poly 0x8005 (reflected 0xA001), as generated by the
    DS28E07. The device transmits it inverted, LSB first."""
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0xA001 if crc & 1 else crc >> 1
    return crc


class DS28E07:
    """DS28E07 1-Wire EEPROM: 128 bytes user memory in 8-byte rows."""

    def __init__(self, pin_name, DMESG=None, LOG=False):
        self.DMESG, self.LOG, self.ow = DMESG, LOG, None

        try:
            self.ow = onewire.OneWire(Pin(pin_name))
            if not self.ow.reset():
                self._log(f"WARN - Pin:{pin_name}, No presence pulse", force=True)
                return
            rom = self._read_rom()
            if rom and crc8(rom[:7]) == rom[7]:
                sn = rom[1:7].hex()
                if rom[0] == _FAMILY_CODE:
                    self._log(f"OK - Pin:{pin_name}, DS28E07 detected, SN={sn}", force=True)
                else:
                    self._log(f"WARN - Pin:{pin_name}, Family {rom[0]:#04x} (expected " +
                              f"{_FAMILY_CODE:#04x}), SN={sn}", force=True)
            else:
                self._log(f"WARN - Pin:{pin_name}, Presence OK but ROM CRC failed", force=True)
        except Exception as e:
            self._log(f"FAIL - Pin:{pin_name}, Error:{e}", force=True)

    def _log(self, msg, force=False):
        if (self.LOG or force) and self.DMESG:
            self.DMESG.log(f"EEPROM[DS28E07]: {msg}")

    # --- Low level ----------------------------------------------------------

    def _read_rom(self):
        """READ ROM (single-drop bus only): family code, 48-bit serial, CRC8."""
        if not self.ow.reset():
            return None
        self.ow.writebyte(_CMD_READ_ROM)
        buf = bytearray(8)
        self.ow.readinto(buf)
        return bytes(buf)

    def _start(self, cmd):
        """Reset + SKIP ROM + memory function command. Returns False if no device."""
        if not self.ow or not self.ow.reset():
            return False
        self.ow.writebyte(_CMD_SKIP_ROM)
        self.ow.writebyte(cmd)
        return True

    def _read_crc16(self, sent):
        """Read the device's inverted CRC-16 (LSB first) and check it against the
        CRC of `sent` (the byte stream as transmitted on the bus)."""
        lo = self.ow.readbyte()
        hi = self.ow.readbyte()
        return ((lo | (hi << 8)) ^ 0xFFFF) == crc16(sent)

    # --- Public API ----------------------------------------------------------

    def read_memory(self, addr, length):
        """READ MEMORY (F0h) from user memory (0-127)."""
        if not (0 <= addr <= 127 and 0 < length <= 128 - addr):
            self._log(f"Invalid read params: addr={addr}, len={length}")
            return None
        try:
            if not self._start(_CMD_READ_MEMORY):
                return None
            self.ow.writebyte(addr & 0xFF)
            self.ow.writebyte(0x00)
            buf = bytearray(length)
            self.ow.readinto(buf)
            self._log(f"Read {length}B @ {addr}")
            return bytes(buf)
        except Exception as e:
            self._log(f"Read error: {e}")
            return None

    def write_memory(self, addr, data):
        """Write via read-modify-write of each affected 8-byte row (the DS28E07
        only copies full, row-aligned scratchpads - see header). Rows whose
        content wouldn't change are skipped to save EEPROM endurance."""
        if not isinstance(data, (bytes, bytearray)):
            data = bytes(data)
        if not (0 <= addr <= 127 and 0 < len(data) <= 128 - addr):
            self._log(f"Invalid write params: addr={addr}, len={len(data)}")
            return False
        try:
            end = addr + len(data)
            for row in range((addr // _ROW) * _ROW, end, _ROW):
                current = self.read_memory(row, _ROW)
                if current is None:
                    return False
                merged = bytearray(current)
                for i in range(_ROW):
                    a = row + i
                    if addr <= a < end:
                        merged[i] = data[a - addr]
                if merged == current:
                    continue
                if not self._write_row(row, bytes(merged)):
                    return False
            verify = self.read_memory(addr, len(data))
            if verify != bytes(data):
                self._log(f"Verify failed @ {addr}")
                return False
            self._log(f"Wrote {len(data)}B @ {addr}")
            return True
        except Exception as e:
            self._log(f"Write error: {e}")
            return False

    # --- Row programming ------------------------------------------------------

    def _write_row(self, row, buf8):
        """Program one aligned 8-byte row: Write Scratchpad + CRC16, Read Scratchpad
        verify (TA/ES/data/CRC16), Copy Scratchpad with authorization, tPROG wait,
        completion check (alternating bits until reset)."""
        # 1) Write Scratchpad. Full row from an aligned address, so E[2:0] reaches
        #    111b and the device appends its inverted CRC-16.
        if not self._start(_CMD_WRITE_SCRATCHPAD):
            return False
        self.ow.writebyte(row & 0xFF)
        self.ow.writebyte(0x00)
        self.ow.write(buf8)
        if not self._read_crc16(bytes([_CMD_WRITE_SCRATCHPAD, row & 0xFF, 0x00]) + buf8):
            self._log(f"Row {row}: Write Scratchpad CRC16 mismatch")
            return False

        # 2) Read Scratchpad: verify address echo, E/S flags, data, and CRC-16.
        if not self._start(_CMD_READ_SCRATCHPAD):
            return False
        ta1 = self.ow.readbyte()
        ta2 = self.ow.readbyte()
        es = self.ow.readbyte()
        if ta1 != (row & 0xFF) or ta2 != 0x00:
            self._log(f"Row {row}: TA echo mismatch ({ta1:#04x},{ta2:#04x})")
            return False
        if es & 0x20:   # PF: data did not arrive intact / partial row
            self._log(f"Row {row}: PF set (partial/corrupt scratchpad)")
            return False
        if (es & 0x07) != 0x07:   # must have filled through the row end
            self._log(f"Row {row}: E/S={es:#04x}, scratchpad not full")
            return False
        sp = bytearray(_ROW)
        self.ow.readinto(sp)
        if not self._read_crc16(bytes([_CMD_READ_SCRATCHPAD, ta1, ta2, es]) + sp):
            self._log(f"Row {row}: Read Scratchpad CRC16 mismatch")
            return False
        if bytes(sp) != buf8:
            self._log(f"Row {row}: scratchpad data mismatch")
            return False

        # 3) Copy Scratchpad with the exact TA1, TA2, E/S authorization pattern.
        if not self._start(_CMD_COPY_SCRATCHPAD):
            return False
        self.ow.writebyte(ta1)
        self.ow.writebyte(ta2)
        self.ow.writebyte(es)

        # 4) tPROG: bus must idle high for parasite power - no polling until done.
        time.sleep_ms(_TPROG_MS)

        # 5) After the copy the device transmits alternating 0s and 1s until reset;
        #    two equal bits mean it is still busy (or the copy was rejected).
        for _ in range(5):
            if self.ow.readbit() != self.ow.readbit():
                return True
            time.sleep_ms(2)
        self._log(f"Row {row}: no completion pattern after copy")
        return False
